### ISSUE TITLE
Screenshot for README

### ISSUE THREAD

**Issue by michael-duke** [mavericks-db/portfolio#15]
## Hey there Mavericks,

My name is Michael, I am a Microverse student and in Module 1 (Week 2). I wanted to know how you made your README screenshot for all devices in one picture. I can't seem to find a tool, can you kindly refer me.

All the best @michael-duke 😄

**Comment by mavericks-db** [comment]
## Hello Michael 😎

Thanks for reaching out. Nice to meet you👍

For your query, below are the two links I used to generate a multi-device website mock-up screenshots:

- [x] [Website Mockup Generator](https://websitemockupgenerator.com/)
- [x] [Multi Device Website Mockup Generator](https://techsini.com/multi-mockup/)

There you go. Have fun with it.
All the best on your Microverse journey💪

---
Cheers 🥂 
@mavericks-db

**Comment by michael-duke** [comment]
> Thank you @mavericks-db
